dj_v1/apps/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path(r"", views.index, name="index"),
    path(r"detail/<int:title_id>/", views.detail, name="detail"),
    path(r"write/", views.write, name="write"),
]

dj_v1/dj_v1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls"))
]

dj_v1/apps/blog/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name="文章标题")
    author = models.CharField(max_length=20, verbose_name="文章作者")
    content = models.TextField(verbose_name="文章内容")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "文章"
        verbose_name_plural = verbose_name

dj_v1/apps/blog/forms.py
from django import forms


class WriteForm(forms.Form):
    title = forms.CharField(max_length=20, required=True)
    author = forms.CharField(max_length=20, required=True)
    content = forms.CharField(widget=forms.Textarea)

dj_v1/apps/blog/views.py
from django.shortcuts import render
from .models import Article
from .forms import WriteForm
from datetime import datetime, date
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.


def index(request):
    titles = Article.objects.order_by("-add_time")
    context = {"titles": titles}
    return render(request, "blog/index.html", context)


def detail(request, title_id):
    article = Article.objects.get(pk=title_id)
    context = {"article": article}
    return render(request, "blog/detail.html", context)


def write(request):
    if request.method == "GET":
        return render(request, "blog/write.html")
    elif request.method == "POST":
        form = WriteForm(request.POST)
        if form.is_valid():
            new_article = Article.objects.create(
                title=request.POST["title"],
                author=request.POST["author"],
                content=request.POST["content"],
                add_time=datetime.now()
            )
            title_id = new_article.id
            return HttpResponseRedirect(reverse("blog:detail", args=[title_id]))
        else:
            return render(request, "blog/write.html")

dj_v1/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="keywords" content="blog, python, django">
    <title>文章详情</title>
</head>
<body>
    <div>
        {% block head %}
        <span>
            <ul>
                <li><a href="{% url 'blog:index' %}">blog</a></li>
                <li><a href="{% url 'blog:write' %}">write</a></li>
            </ul>
        </span>
        {% endblock %}
        <span>
            <h1>{{ article.title }}</h1>
            <small>By-{{ article.author }} &#160 &#160 {{ article.add_time }}</small>
            <p>{{ article.content }}</p>
        </span>
    </div>
</body>
</html>

dj_v1/templates/blog/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="description" content="blog, python, django, lzn202">
    <title>首页</title>
</head>
<body>
    <div>
        <span>
            <ul>
                <li><a href="{% url 'blog:index' %}">blog</a></li>
                <li><a href="{% url 'blog:write' %}">write</a></li>
            </ul>
        </span>
        <div>
            <ul>
                {% for title in titles %}
                <li>
                    <a href="{% url 'blog:detail' title.id %}"><h1>{{ title.title }}</h1></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>

dj_v1/templates/blog/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编写文章</title>
</head>
<body>
    <div>
        {% include "blog/detail.html" %}
        <form action="{% url 'blog:write' %}" method="POST" name="article" target="_blank" accept-charset="UTF-8">

            <b>文章标题:</b>
            <br/>
            <input name="title" type="text" maxlength="20" />
            <br/>

            <b>文章作者:</b>
            <br/>
            <input name="author" type="text" maxlength="20" />
            <br/>

            <b>文章内容:</b>
            <br/>
            <textarea name="content" rows="20" cols="50">
            </textarea>
            <br/>

            <input type="submit" name="send" value="提交" />
            {% csrf_token %}
        </form>
    </div>
</body>
</html>